/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @copyright   (c) 2015 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @brief       Type traits
 */

#ifndef XS_ATOMIC_TRAITS_H
#define XS_ATOMIC_TRAITS_H

#include <type_traits>

#define XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD( _N_, _F_ )                                                    \
    template< typename _T_, typename _R_, typename ... _A_ >                                                \
    class _N_                                                                                               \
    {                                                                                                       \
        private:                                                                                            \
                                                                                                            \
            struct _Y { char _[ 1 ]; };                                                                     \
            struct _N { char _[ 2 ]; };                                                                     \
                                                                                                            \
            template< typename _U_, _U_ > struct _S;                                                        \
                                                                                                            \
            template< typename _C_ > static _Y & _T( _S< _R_ ( _C_::* )( _A_ ... ), &_C_::_F_ > * );        \
            template< typename _C_ > static _N & _T( ... );                                                 \
                                                                                                            \
        public:                                                                                             \
                                                                                                            \
            enum { value = sizeof( _T< _T_ >( 0 ) ) == sizeof( _Y ) };                                      \
    }

#define XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( _N_, _F_ )                                              \
    template< typename _T_, typename _R_, typename ... _A_ >                                                \
    class _N_                                                                                               \
    {                                                                                                       \
        private:                                                                                            \
                                                                                                            \
            struct _Y { char _[ 1 ]; };                                                                     \
            struct _N { char _[ 2 ]; };                                                                     \
                                                                                                            \
            template< typename _U_, _U_ > struct _S;                                                        \
                                                                                                            \
            template< typename _C_ > static _Y & _T( _S< _R_ ( _C_::* )( _A_ ... ) const, &_C_::_F_ > * );  \
            template< typename _C_ > static _N & _T( ... );                                                 \
                                                                                                            \
        public:                                                                                             \
                                                                                                            \
            enum { value = sizeof( _T< _T_ >( 0 ) ) == sizeof( _Y ) };                                      \
    }

namespace XS
{
    namespace TypeTraits
    {
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasSimpleAssignmentOperator,            operator = );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasAdditionAssignmentOperator,          operator += );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasSubtractionAssignmentOperator,       operator -= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasMultiplicationAssignmentOperator,    operator *= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasDivisionAssignmentOperator,          operator /= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasModuloAssignmentOperator,            operator %= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasBitwiseANDAssignmentOperator,        operator &= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasBitwiseORAssignmentOperator,         operator |= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasBitwiseXORAssignmentOperator,        operator ^= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasBitwiseLeftShiftAssignmentOperator,  operator <<= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasBitwiseRightShiftAssignmentOperator, operator >>= );
        
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasPreIncrementOperator,                operator ++ );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasPreDecrementOperator,                operator -- );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasPostIncrementOperator,               operator ++ );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasPostDecrementOperator,               operator -- );
        
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasUnaryPlusOperator,                   operator + );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasUnaryMinusOperator,                  operator - );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasAdditionOperator,                    operator + );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasSubtractionOperator,                 operator - );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasMultiplicationOperator,              operator * );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasDivisionOperator,                    operator / );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasModuloOperator,                      operator % );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasBitwiseNOTOperator,                  operator ~ );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasBitwiseANDOperator,                  operator & );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasBitwiseOROperator,                   operator | );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasBitwiseXOROperator,                  operator ^ );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasBitwiseLeftShiftOperator,            operator << );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasBitwiseLightShiftOperator,           operator >> );
        
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasNegationOperator,                    operator ! );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasANDOperator,                         operator && );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasInclusiveOROperator,                 operator || );
        
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasEqualToOperator,                     operator == );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasNotEqualToOperator,                  operator != );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasLessThanOperator,                    operator < );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasGreaterThanOperator,                 operator > );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasLessThanOrEqualToOperator,           operator <= );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_CONST_METHOD( HasGreaterThanOrEqualToOperator,        operator >= );
        
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasSubscriptOperator,                   operator [] );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasIndirectionOperator,                 operator * );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasAddressOfOperator,                   operator & );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasMemberOfPointerOperator,             operator -> );
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasPointerToMemberOfPointerOperator,    operator ->* );
        
        XS_TYPE_TRAITS_DEF_HAS_PUBLIC_METHOD(       HasFunctionCallOperator,                operator () );
        
        template< typename _T_, typename _R_, typename ... _A_ >
        class HasCommaOperator
        {
            private:
                
                struct _Y { char _[ 1 ]; };
                struct _N { char _[ 2 ]; };
                
                template< typename _U_, _U_ > struct _S;
                
                template< typename _C_ > static _Y & _T( _S< _R_ ( _C_::* )( _A_ ... ), &_C_::_F_ > * );
                template< typename _C_ > static _N & _T( ... );
                
            public:
                
                enum { value = sizeof( _T< _T_ >( 0 ) ) == sizeof( _Y ) };
        };
    }
}

#endif /* XS_ATOMIC_TRAITS_H */
