/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @copyright   (c) 2015 - Jean-David Gadina - www.xs-labs.com
 * @brief       Replacement of std::atomic supporting non trivially-copyable types
 */

#ifndef XS_ATOMIC_TRIVIAL_H
#define XS_ATOMIC_TRIVIAL_H

#include <type_traits>
#include <utility>
#include <atomic>
#include <mutex>

namespace XS
{
    /*!
     * @class           Atomic
     * @abstract        ...
     * @templatefield   _T_     ...
     * @discussion      ...
     */
    template< typename _T_ >
    class Atomic< _T_, typename std::enable_if< std::is_trivially_copyable< _T_ >::value >::type >
    {
        private:
            
            typedef std::atomic< _T_ >      _A_;
            typedef std::recursive_mutex    _M_;
            typedef std::lock_guard< _M_ >  _L_;
            
            _A_ _v;
            _M_ _m;
            
            template< class _U_ >
            struct IsEqualityComparable: public std::integral_constant< bool, std::is_same< _U_ , bool >::value || std::is_integral< _U_ >::value || std::is_pointer< _U_ >::value >
            {};
            
            template< class _U_ >
            struct IsArithmetic: public std::integral_constant< bool, !std::is_same< _U_ , bool >::value && ( std::is_integral< _U_ >::value || std::is_pointer< _U_ >::value || std::is_floating_point< _U_ >::value ) >
            {};
            
            template< class _U_ >
            struct IsBitwise: public std::integral_constant< bool, std::is_integral< _U_ >::value && std::is_unsigned< _U_ >::value >
            {};
        
        public:
            
            /*******************************************************************
             * Common definitions
             ******************************************************************/
            
            Atomic( void ): _v{}
            {}
            
            Atomic( _T_ v ): _v{ v }
            {}
            
            Atomic( const Atomic< _T_ > & o ): _v{ o._v.load() }
            {}
            
            Atomic( const Atomic< _T_ > && o ) = delete;
            
            ~Atomic( void )
            {}
            
            Atomic< _T_ > & operator =( Atomic< _T_ > o )
            {
                this->_v = o._v.load();
                
                return *( this );
            }
            
            Atomic< _T_ > & operator =( _T_ v )
            {
                this->_v = v;
                
                return *( this );
            }
            
            operator _T_ ( void ) const
            {
                return this->_v;
            }
            
            _T_ Load( void )
            {
                return this->_v.load();
            }
            
            void Store( _T_ v )
            {
                this->_v.store( v );
            }
            
            bool IsLockFree( void ) const
            {
                return this->_v.is_lock_free();
            }
            
            friend void swap( Atomic< _T_ > & o1, Atomic< _T_ > & o2 )
            {
                std::lock( o1._m, o2._m );
                
                _L_ l1( o1._m, std::adopt_lock );
                _L_ l2( o2._m, std::adopt_lock );
                
                _T_ v1 = o1._v.load();
                _T_ v2 = o2._v.load();
                
                o1._v.store( v2 );
                o2._v.store( v1 );
            }
            
            /*******************************************************************
             * Equality comparable
             ******************************************************************/
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsEqualityComparable< _U_ >::value > >
            bool operator ==( const Atomic< _T_ > & o ) const
            {
                return this->_v == o._v;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsEqualityComparable< _U_ >::value > >
            bool operator ==( _T_ v ) const
            {
                return this->_v == v;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsEqualityComparable< _U_ >::value > >
            bool operator !=( const Atomic< _T_ > & o ) const
            {
                return !operator ==( o );
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsEqualityComparable< _U_ >::value > >
            bool operator !=( _T_ v ) const
            {
                return !operator ==( v );
            }
            
            /*******************************************************************
             * Arithmetic
             ******************************************************************/
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            bool operator >( _T_ v ) const
            {
                return this->_v.load() > v;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            bool operator <( _T_ v ) const
            {
                return this->_v.load() < v;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            bool operator >=( _T_ v ) const
            {
                return this->_v.load() >= v;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            bool operator <=( _T_ v ) const
            {
                return this->_v.load() <= v;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            Atomic< _T_ > & operator ++ ( void )
            {
                this->_v++;
                
                return *( this );
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            Atomic< _T_ > operator ++ ( int )
            {
                Atomic< _T_ > a( *( this ) );
                
                operator++();
                
                return a;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            Atomic< _T_ > & operator -- ( void )
            {
                this->_v--;
                
                return *( this );
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            Atomic< _T_ > operator -- ( int )
            {
                Atomic< _T_ > a( *( this ) );
                
                operator--();
                
                return a;
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            Atomic< _T_ > & operator += ( _T_ v )
            {
                this->_v += v;
                
                return *( this );
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsArithmetic< _U_ >::value > >
            Atomic< _T_ > & operator -= ( _T_ v )
            {
                this->_v -= v;
                
                return *( this );
            }
            
            /*******************************************************************
             * Bitwise
             ******************************************************************/
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsBitwise< _U_ >::value > >
            Atomic< _T_ > & operator &= ( _T_ v )
            {
                this->_v &= v;
                
                return *( this );
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsBitwise< _U_ >::value > >
            Atomic< _T_ > & operator |= ( _T_ v )
            {
                this->_v |= v;
                
                return *( this );
            }
            
            template< typename _U_ = _T_, typename = typename std::enable_if< std::is_same< _U_, _T_ >::value && IsBitwise< _U_ >::value > >
            Atomic< _T_ > & operator ^= ( _T_ v )
            {
                this->_v ^= v;
                
                return *( this );
            }
    };
}

#endif /* XS_ATOMIC_TRIVIAL_H */
