/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @copyright   (c) 2015 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @brief       Test case XS::Atomic
 */

/* Disabled warnings for GoogleMock */
#ifdef __clang__
#pragma clang diagnostic ignored "-Wglobal-constructors"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic push
#if __clang_major__ >= 7
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#pragma clang diagnostic ignored "-Wmissing-noreturn"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic ignored "-Wused-but-marked-unused"
#pragma clang diagnostic ignored "-Wdeprecated"
#endif

#include <GoogleMock/GoogleMock.h>

#ifdef __clang__
#pragma clang diagnostic pop
#endif

#include <XS/Atomic.hpp>

using namespace testing;

/*******************************************************************************
 * Common definitions
 ******************************************************************************/
             
TEST( XS_Atomic_Trivial_Bool, CTOR )
{
    XS::Atomic< bool > a;
    
    ASSERT_TRUE( a == false );
}

TEST( XS_Atomic_Trivial_Bool, CTOR_V )
{
    XS::Atomic< bool > a1{ true };
    XS::Atomic< bool > a2{ false };
    
    ASSERT_TRUE( a1 == true );
    ASSERT_TRUE( a2 == false );
}

TEST( XS_Atomic_Trivial_Bool, CCTOR )
{
    XS::Atomic< bool > a1{ true };
    XS::Atomic< bool > a2{ a1 };
    
    ASSERT_TRUE( a1 == true );
    ASSERT_TRUE( a2 == true );
}

TEST( XS_Atomic_Trivial_Bool, OperatorAssign )
{
    XS::Atomic< bool > a1{ true };
    XS::Atomic< bool > a2;
    
    a2 = a1;
    
    ASSERT_TRUE( a1 == true );
    ASSERT_TRUE( a2 == true );
}

TEST( XS_Atomic_Trivial_Bool, OperatorAssign_V )
{
    XS::Atomic< bool > a;
    
    a = true;
    
    ASSERT_TRUE( a == true );
}

TEST( XS_Atomic_Trivial_Bool, OperatorCast )
{
    XS::Atomic< bool > a1{ true };
    XS::Atomic< bool > a2{ false };
    
    ASSERT_TRUE( static_cast< bool >( a1 ) == true );
    ASSERT_TRUE( static_cast< bool >( a2 ) == false );
}

TEST( XS_Atomic_Trivial_Bool, Load )
{
    XS::Atomic< bool > a1{ true };
    XS::Atomic< bool > a2{ false };
    
    ASSERT_TRUE( a1.Load() == true );
    ASSERT_TRUE( a2.Load() == false );
}

TEST( XS_Atomic_Trivial_Bool, Store )
{
    XS::Atomic< bool > a;
    
    a.Store( true );
    
    ASSERT_TRUE( a == true );
}

TEST( XS_Atomic_Trivial_Bool, Swap )
{
    XS::Atomic< bool > a1{ true };
    XS::Atomic< bool > a2{ false };
    
    ASSERT_TRUE( a1 == true );
    ASSERT_TRUE( a2 == false );
    
    swap( a1, a2 );
    
    ASSERT_TRUE( a1 == false );
    ASSERT_TRUE( a2 == true );
}

/*******************************************************************************
 * Type specific
 ******************************************************************************/

TEST( XS_Atomic_Trivial_Bool, SimpleAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, AdditionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, SubtractionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, MultiplicationAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, DivisionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, ModuloAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseANDAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseORAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseXORAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseLeftShiftAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseRightShiftAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Bool, PreIncrementOperator )
{}

TEST( XS_Atomic_Trivial_Bool, PreDecrementOperator )
{}

TEST( XS_Atomic_Trivial_Bool, PostIncrementOperator )
{}

TEST( XS_Atomic_Trivial_Bool, PostDecrementOperator )
{}

TEST( XS_Atomic_Trivial_Bool, UnaryPlusOperator )
{}

TEST( XS_Atomic_Trivial_Bool, UnaryMinusOperator )
{}

TEST( XS_Atomic_Trivial_Bool, AdditionOperator )
{}

TEST( XS_Atomic_Trivial_Bool, SubtractionOperator )
{}

TEST( XS_Atomic_Trivial_Bool, MultiplicationOperator )
{}

TEST( XS_Atomic_Trivial_Bool, DivisionOperator )
{}

TEST( XS_Atomic_Trivial_Bool, ModuloOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseNOTOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseANDOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseOROperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseXOROperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseLeftShiftOperator )
{}

TEST( XS_Atomic_Trivial_Bool, BitwiseLightShiftOperator )
{}

TEST( XS_Atomic_Trivial_Bool, NegationOperator )
{}

TEST( XS_Atomic_Trivial_Bool, ANDOperator )
{}

TEST( XS_Atomic_Trivial_Bool, InclusiveOROperator )
{}

TEST( XS_Atomic_Trivial_Bool, EqualToOperator )
{}

TEST( XS_Atomic_Trivial_Bool, NotEqualToOperator )
{}

TEST( XS_Atomic_Trivial_Bool, LessThanOperator )
{}

TEST( XS_Atomic_Trivial_Bool, GreaterThanOperator )
{}

TEST( XS_Atomic_Trivial_Bool, LessThanOrEqualToOperator )
{}

TEST( XS_Atomic_Trivial_Bool, GreaterThanOrEqualToOperator )
{}
