/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @copyright   (c) 2015 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @brief       Test case XS::Atomic
 */

/* Disabled warnings for GoogleMock */
#ifdef __clang__
#pragma clang diagnostic ignored "-Wglobal-constructors"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic push
#if __clang_major__ >= 7
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#pragma clang diagnostic ignored "-Wmissing-noreturn"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic ignored "-Wused-but-marked-unused"
#pragma clang diagnostic ignored "-Wdeprecated"
#endif

#include <GoogleMock/GoogleMock.h>

#ifdef __clang__
#pragma clang diagnostic pop
#endif

#include <XS/Atomic.hpp>

using namespace testing;

static bool DoubleIsEqual( double x, double y );
static bool DoubleIsEqual( double x, double y )
{
    return fabs( x - y ) < DBL_EPSILON;
}

/*******************************************************************************
 * Common definitions
 ******************************************************************************/

TEST( XS_Atomic_Trivial_Double, CTOR )
{
    XS::Atomic< double > a;
    
    ASSERT_TRUE( DoubleIsEqual( a, 0.0 ) );
}

TEST( XS_Atomic_Trivial_Double, CTOR_V )
{
    XS::Atomic< double > a{ 42.0 };
    
    ASSERT_TRUE( DoubleIsEqual( a, 42.0 ) );
}

TEST( XS_Atomic_Trivial_Double, CCTOR )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ a1 };
    
    ASSERT_TRUE( DoubleIsEqual( a1, 42.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

TEST( XS_Atomic_Trivial_Double, OperatorAssign )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2;
    
    a2 = a1;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 42.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

TEST( XS_Atomic_Trivial_Double, OperatorAssign_V )
{
    XS::Atomic< double > a;
    
    a = 42.0;
    
    ASSERT_TRUE( DoubleIsEqual( a, 42.0 ) );
}

TEST( XS_Atomic_Trivial_Double, OperatorCast )
{
    XS::Atomic< double > a{ 42.0 };
    
    ASSERT_TRUE( DoubleIsEqual( static_cast< double >( a ), 42.0 ) );
}

TEST( XS_Atomic_Trivial_Double, Load )
{
    XS::Atomic< double > a{ 42.0 };
    
    ASSERT_TRUE( DoubleIsEqual( a.Load(), 42.0 ) );
}

TEST( XS_Atomic_Trivial_Double, Store )
{
    XS::Atomic< double > a;
    
    a.Store( 42.0 );
    
    ASSERT_TRUE( DoubleIsEqual( a, 42.0 ) );
}

TEST( XS_Atomic_Trivial_Double, Swap )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 43.0 };
    
    ASSERT_TRUE( DoubleIsEqual( a1, 42.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 43.0 ) );
    
    swap( a1, a2 );
    
    ASSERT_TRUE( DoubleIsEqual( a1, 43.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

/*******************************************************************************
 * Type specific
 ******************************************************************************/

TEST( XS_Atomic_Trivial_Double, AdditionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, SubtractionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, MultiplicationAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, DivisionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, ModuloAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseANDAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseORAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseXORAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseLeftShiftAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseRightShiftAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Double, PreIncrementOperator )
{}

TEST( XS_Atomic_Trivial_Double, PreDecrementOperator )
{}

TEST( XS_Atomic_Trivial_Double, PostIncrementOperator )
{}

TEST( XS_Atomic_Trivial_Double, PostDecrementOperator )
{}

TEST( XS_Atomic_Trivial_Double, UnaryPlusOperator )
{}

TEST( XS_Atomic_Trivial_Double, UnaryMinusOperator )
{}

TEST( XS_Atomic_Trivial_Double, AdditionOperator )
{}

TEST( XS_Atomic_Trivial_Double, SubtractionOperator )
{}

TEST( XS_Atomic_Trivial_Double, MultiplicationOperator )
{}

TEST( XS_Atomic_Trivial_Double, DivisionOperator )
{}

TEST( XS_Atomic_Trivial_Double, ModuloOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseNOTOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseANDOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseOROperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseXOROperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseLeftShiftOperator )
{}

TEST( XS_Atomic_Trivial_Double, BitwiseLightShiftOperator )
{}

TEST( XS_Atomic_Trivial_Double, NegationOperator )
{}

TEST( XS_Atomic_Trivial_Double, ANDOperator )
{}

TEST( XS_Atomic_Trivial_Double, InclusiveOROperator )
{}

TEST( XS_Atomic_Trivial_Double, EqualToOperator )
{}

TEST( XS_Atomic_Trivial_Double, NotEqualToOperator )
{}

TEST( XS_Atomic_Trivial_Double, LessThanOperator )
{}

TEST( XS_Atomic_Trivial_Double, GreaterThanOperator )
{}

TEST( XS_Atomic_Trivial_Double, LessThanOrEqualToOperator )
{}

TEST( XS_Atomic_Trivial_Double, GreaterThanOrEqualToOperator )
{}
