/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @copyright   (c) 2015 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @brief       Test case XS::Atomic
 */

/* Disabled warnings for GoogleMock */
#ifdef __clang__
#pragma clang diagnostic ignored "-Wglobal-constructors"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic push
#if __clang_major__ >= 7
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#pragma clang diagnostic ignored "-Wmissing-noreturn"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic ignored "-Wused-but-marked-unused"
#pragma clang diagnostic ignored "-Wdeprecated"
#endif

#include <GoogleMock/GoogleMock.h>

#ifdef __clang__
#pragma clang diagnostic pop
#endif

#include <XS/Atomic.hpp>

using namespace testing;

/*******************************************************************************
 * Common definitions
 ******************************************************************************/

TEST( XS_Atomic_Trivial_Integral, CTOR )
{
    XS::Atomic< int > a;
    
    ASSERT_TRUE( a == 0 );
}

TEST( XS_Atomic_Trivial_Integral, CTOR_V )
{
    XS::Atomic< int > a{ 42 };
    
    ASSERT_TRUE( a == 42 );
}

TEST( XS_Atomic_Trivial_Integral, CCTOR )
{
    XS::Atomic< int > a1{ 42 };
    XS::Atomic< int > a2{ a1 };
    
    ASSERT_TRUE( a1 == 42 );
    ASSERT_TRUE( a2 == 42 );
}

TEST( XS_Atomic_Trivial_Integral, OperatorAssign )
{
    XS::Atomic< int > a1{ 42 };
    XS::Atomic< int > a2;
    
    a2 = a1;
    
    ASSERT_TRUE( a1 == 42 );
    ASSERT_TRUE( a2 == 42 );
}

TEST( XS_Atomic_Trivial_Integral, OperatorAssign_V )
{
    XS::Atomic< int > a;
    
    a = 42;
    
    ASSERT_TRUE( a == 42 );
}

TEST( XS_Atomic_Trivial_Integral, OperatorCast )
{
    XS::Atomic< int > a{ 42 };
    
    ASSERT_TRUE( static_cast< int >( a ) == 42 );
}

TEST( XS_Atomic_Trivial_Integral, Load )
{
    XS::Atomic< int > a{ 42 };
    
    ASSERT_TRUE( a == 42 );
}

TEST( XS_Atomic_Trivial_Integral, Store )
{
    XS::Atomic< int > a;
    
    a.Store( 42 );
    
    ASSERT_TRUE( a == 42 );
}

TEST( XS_Atomic_Trivial_Integral, Swap )
{
    XS::Atomic< int > a1{ 42 };
    XS::Atomic< int > a2{ 43 };
    
    ASSERT_TRUE( a1 == 42 );
    ASSERT_TRUE( a2 == 43 );
    
    swap( a1, a2 );
    
    ASSERT_TRUE( a1 == 43 );
    ASSERT_TRUE( a2 == 42 );
}

/*******************************************************************************
 * Type specific
 ******************************************************************************/

TEST( XS_Atomic_Trivial_Integral, AdditionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, AdditionAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, SubtractionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, SubtractionAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, MultiplicationAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, MultiplicationAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, DivisionAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, DivisionAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, ModuloAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, ModuloAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseANDAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseANDAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseORAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseORAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseXORAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseXORAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseLeftShiftAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseLeftShiftAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseRightShiftAssignmentOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseRightShiftAssignmentOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, PreIncrementOperator )
{}

TEST( XS_Atomic_Trivial_Integral, PreDecrementOperator )
{}

TEST( XS_Atomic_Trivial_Integral, PostIncrementOperator )
{}

TEST( XS_Atomic_Trivial_Integral, PostDecrementOperator )
{}

TEST( XS_Atomic_Trivial_Integral, UnaryPlusOperator )
{}

TEST( XS_Atomic_Trivial_Integral, UnaryMinusOperator )
{}

TEST( XS_Atomic_Trivial_Integral, AdditionOperator )
{}

TEST( XS_Atomic_Trivial_Integral, AdditionOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, SubtractionOperator )
{}

TEST( XS_Atomic_Trivial_Integral, SubtractionOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, MultiplicationOperator )
{}

TEST( XS_Atomic_Trivial_Integral, MultiplicationOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, DivisionOperator )
{}

TEST( XS_Atomic_Trivial_Integral, DivisionOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, ModuloOperator )
{}

TEST( XS_Atomic_Trivial_Integral, ModuloOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseANDOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseANDOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseOROperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseOROperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseXOROperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseXOROperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseLeftShiftOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseLeftShiftOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseLightShiftOperator )
{}

TEST( XS_Atomic_Trivial_Integral, BitwiseLightShiftOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, NegationOperator )
{}

TEST( XS_Atomic_Trivial_Integral, ANDOperator )
{}

TEST( XS_Atomic_Trivial_Integral, ANDOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, InclusiveOROperator )
{}

TEST( XS_Atomic_Trivial_Integral, InclusiveOROperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, EqualToOperator )
{}

TEST( XS_Atomic_Trivial_Integral, EqualToOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, NotEqualToOperator )
{}

TEST( XS_Atomic_Trivial_Integral, NotEqualToOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, LessThanOperator )
{}

TEST( XS_Atomic_Trivial_Integral, LessThanOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, GreaterThanOperator )
{}

TEST( XS_Atomic_Trivial_Integral, GreaterThanOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, LessThanOrEqualToOperator )
{}

TEST( XS_Atomic_Trivial_Integral, LessThanOrEqualToOperator_V )
{}

TEST( XS_Atomic_Trivial_Integral, GreaterThanOrEqualToOperator )
{}

TEST( XS_Atomic_Trivial_Integral, GreaterThanOrEqualToOperator_V )
{}
