/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @copyright   (c) 2015 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @brief       Test case XS::Atomic
 */

/* Disabled warnings for GoogleMock */
#ifdef __clang__
#pragma clang diagnostic ignored "-Wglobal-constructors"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic push
#if __clang_major__ >= 7
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#pragma clang diagnostic ignored "-Wmissing-noreturn"
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic ignored "-Wused-but-marked-unused"
#pragma clang diagnostic ignored "-Wdeprecated"
#endif

#include <GoogleMock/GoogleMock.h>

#ifdef __clang__
#pragma clang diagnostic pop
#endif

#include <XS/Atomic.hpp>

using namespace testing;

static bool DoubleIsEqual( double x, double y );
static bool DoubleIsEqual( double x, double y )
{
    return fabs( x - y ) < DBL_EPSILON;
}

/*******************************************************************************
 * Common definitions
 ******************************************************************************/

TEST( XS_Atomic_Trivial_double, CTOR )
{
    XS::Atomic< double > a;
    
    ASSERT_TRUE( DoubleIsEqual( a, 0.0 ) );
}

TEST( XS_Atomic_Trivial_double, CTOR_V )
{
    XS::Atomic< double > a{ 42.0 };
    
    ASSERT_TRUE( DoubleIsEqual( a, 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, CCTOR )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ a1 };
    
    ASSERT_TRUE( DoubleIsEqual( a1, 42.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorAssign )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2;
    
    a2 = a1;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 42.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorAssign_V )
{
    XS::Atomic< double > a;
    
    a = 42.0;
    
    ASSERT_TRUE( DoubleIsEqual( a, 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorCast )
{
    XS::Atomic< double > a{ 42.0 };
    
    ASSERT_TRUE( DoubleIsEqual( static_cast< double >( a ), 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, Load )
{
    XS::Atomic< double > a{ 42.0 };
    
    ASSERT_TRUE( DoubleIsEqual( a.Load(), 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, Store )
{
    XS::Atomic< double > a;
    
    a.Store( 42.0 );
    
    ASSERT_TRUE( DoubleIsEqual( a, 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, Swap )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 43.0 };
    
    ASSERT_TRUE( DoubleIsEqual( a1, 42.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 43.0 ) );
    
    swap( a1, a2 );
    
    ASSERT_TRUE( DoubleIsEqual( a1, 43.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

/*******************************************************************************
 * Arithmetic
 ******************************************************************************/

TEST( XS_Atomic_Trivial_double, OperatorGreater )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 42.0 };
    XS::Atomic< double > a3{ 43.0 };
    
    ASSERT_TRUE(  a3 > a1 );
    ASSERT_FALSE( a1 > a2 );
    ASSERT_FALSE( a1 > a3 );
}

TEST( XS_Atomic_Trivial_double, OperatorGreater_V )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 43.0 };
    
    ASSERT_TRUE(  a2 > 42.0 );
    ASSERT_FALSE( a1 > 42.0 );
    ASSERT_FALSE( a1 > 43.0 );
}

TEST( XS_Atomic_Trivial_double, OperatorLesser )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 42.0 };
    XS::Atomic< double > a3{ 43.0 };
    
    ASSERT_TRUE(  a1 < a3 );
    ASSERT_FALSE( a1 < a2 );
    ASSERT_FALSE( a3 < a1 );
}

TEST( XS_Atomic_Trivial_double, OperatorLesser_V )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 43.0 };
    
    ASSERT_TRUE(  a1 < 43.0 );
    ASSERT_FALSE( a2 < 43.0 );
    ASSERT_FALSE( a1 < 42.0 );
}

TEST( XS_Atomic_Trivial_double, OperatorGreaterEqual )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 42.0 };
    XS::Atomic< double > a3{ 43.0 };
    
    ASSERT_TRUE(  a3 >= a1 );
    ASSERT_TRUE(  a1 >= a2 );
    ASSERT_FALSE( a1 >= a3 );
}

TEST( XS_Atomic_Trivial_double, OperatorGreaterEqual_V )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 43.0 };
    
    ASSERT_TRUE(  a2 >= 42.0 );
    ASSERT_TRUE(  a1 >= 42.0 );
    ASSERT_FALSE( a1 >= 43.0 );
}

TEST( XS_Atomic_Trivial_double, OperatorLesserEqual )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 42.0 };
    XS::Atomic< double > a3{ 43.0 };
    
    ASSERT_TRUE(  a1 <= a3 );
    ASSERT_TRUE(  a1 <= a2 );
    ASSERT_FALSE( a3 <= a1 );
}

TEST( XS_Atomic_Trivial_double, OperatorLesserEqual_V )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 43.0 };
    
    ASSERT_TRUE(  a1 <= 43.0 );
    ASSERT_TRUE(  a1 <= 42.0 );
    ASSERT_FALSE( a2 <= 42.0 );
}

/*
TEST( XS_Atomic_Trivial_double, OperatorPreIncrement )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2;
    
    a2 = ++a1;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 43.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 43.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorPostIncrement )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2;
    
    a2 = a1++;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 43.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorPreDecrement )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2;
    
    a2 = --a1;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 41.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 41.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorPostDecrement )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2;
    
    a2 = a1--;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 41.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 42.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorPlusEqual )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 10.0 };
    
    a1 += a2;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 52.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 10.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorPlusEqual_V )
{
    XS::Atomic< double > a{ 42.0 };
    
    a += 10.0;
    
    ASSERT_TRUE( DoubleIsEqual( a, 52.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorMinusEqual )
{
    XS::Atomic< double > a1{ 42.0 };
    XS::Atomic< double > a2{ 10.0 };
    
    a1 -= a2;
    
    ASSERT_TRUE( DoubleIsEqual( a1, 32.0 ) );
    ASSERT_TRUE( DoubleIsEqual( a2, 10.0 ) );
}

TEST( XS_Atomic_Trivial_double, OperatorMinusEqual_V )
{
    XS::Atomic< double > a{ 42.0 };
    
    a -= 10.0;
    
    ASSERT_TRUE( DoubleIsEqual( a, 32.0 ) );
}
*/
